### PR TITLE
Update tool_and_resource_list.yml

### PR DESCRIPTION
**Pull request by katemichie**
Add in link to Australian Alphafold service

### CODE REVIEW

**Comment by keiran-rowell-unsw** [comment]
Looks like your found it, but Johan set up a[ Google Sheet](https://docs.google.com/spreadsheets/d/1OYx8cp4kQ7g3_Z39NDSH5325WvpZKSsjwKBiiRS9Xs8/edit?usp=sharing) that allows invited people to add links to the spreadsheet without having to learn git. This is the preferred way to add a link as Johan set up [GitHub action](https://github.com/Australian-Structural-Biology-Computing/website/actions/workflows/update_guides.yml) that which easily and automatically pulls from the sheet's contents and rebuilds on the website.

**Comment by keiran-rowell-unsw** [comment]
Looks like your found it, but Johan set up a [Google Sheet ](https://docs.google.com/spreadsheets/d/1OYx8cp4kQ7g3_Z39NDSH5325WvpZKSsjwKBiiRS9Xs8/edit?usp=sharing) that allows invited people to add links to the spreadsheet without having to learn git. This is the preferred way to add a link as Johan set up [GitHub action](https://github.com/Australian-Structural-Biology-Computing/website/actions/workflows/update_guides.yml) that which easily and automatically pulls from the sheet's contents and rebuilds on the website.

**Comment by katemichie** [comment]
Ok, sorry, just realised when I went through the talk that I needed to direct people to it and it wasn’t there. I’ll learn more about the google sheets when I return and get it right

Hope you had a good weekend.

Many thanks.

Cheers
K


_______________________________

Dr Kate Michie
Chief Scientist - Structural Biology Facility, MWAC

Senior Lecturer-  BABS UNSW



[signature_2063424362]





Office Workspace 320, Level 3 West,
Biosciences North D26
University of New South Wales
Sydney, NSW 2052
Australia

https://www.analytical.unsw.edu.au/facilities/sbf

mob: 0426837767<tel:0426837767>
T: +61 (2) 9385 4587<tel:+61%20(2)%209385%204587>

________________________________

**Comment by keiran-rowell-unsw** [comment]
Oh no problem at all! That change also would have worked, but the Google Sheet should make it easier for non-Git users to add in their useful links when give edit access to the spreadsheet.

Yep, it was a great weekend. I hope you had a good one to!

Thanks.

**Pull request closed without merging**
